### ISSUE TITLE
Caption Embedding

### ISSUE THREAD

**Issue by ballerabdude** [szatmary/libcaption#13]
This is a really really cool and useful lib. A cool feature would be the ability to embed 608 captions into a h264 video elementary stream.

**Comment by szatmary** [comment]
@ballerabdude This does support embedding in h.264. (check avc.c)

**Comment by ballerabdude** [comment]
Nice! I am trying to follow your flv+scc.c code to create an h264 version and I am having a hard time. My c knowledge is very limited. If you can give me steps to follow to embed an scc caption file into an h264 or create an example I would really appreciate it.

**Comment by szatmary** [comment]
Take a look at add_caption.sh

**Comment by ballerabdude** [comment]
You are awesome wish I can buy you a beer or coffee. I was using a caption file for a different video expecting it to work. Also is there a way to embed the caption into the h264 stream without encoding?

**Comment by szatmary** [comment]
That script doesn't encode. It uses `-codec copy`

**Comment by ballerabdude** [comment]
I'm an idiot. I was running the second example ffmpeg command. One more question why does it have to be copied to an flv? For the past few months I have been looking for a project like yours. At work we ended up buying a really expensive 608 caption inserting solution. I can't wait to get some time to learn C and help you out. I will definitely send in a pull request with some documentation I would like to add. I want to ask more questions about inserting 708 as well but I can save that for another time. You have been super helpful.

**Comment by szatmary** [comment]
It doesn't need to be FLV, it is just the most simple container format. This does use 708 to encapsulate 608. I started working on full 708 (see dvtcc.c) But I currently don't use it at work, so its slow going. I developed this specifically because I believe captions should be free (or at east very cheep)

**Comment by ballerabdude** [comment]
What resource did you use to learn about the caption insertion process that allowed you to write this?

**Comment by szatmary** [comment]
@ballerabdude  actually, if you have some .mcc (708) files It would probably speed up development.

**Comment by szatmary** [comment]
Wikipedia and a hex editor.

**Comment by ballerabdude** [comment]
Nice never heard of .mcc files. Looks like I better download a hex editor. I never used one.

**Comment by ridhimrastogi** [comment]
@szatmary  Did you make any progress with the native 708?

**Comment by leeerickson2050** [comment]
anyone have a simple windows exe to embed cc608 or 708 into h.264? Please help..

**Comment by ballerabdude** [comment]
@leeerickson2050 I think the whole lib is written using the standard C lib. You can try to integrate it into a Go program then compile it to run in windows.
