### ISSUE TITLE
Text Metadata missing

### ISSUE THREAD

**Issue by ballerabdude** [szatmary/libcaption#18]
On the latest build as of 5-31-2017 the text metadata is missing after embedding captions. 
The captions are definitely in the video stream but the metadata is not updated after I run mediainfo on it.

![image](https://cloud.githubusercontent.com/assets/7660642/26637420/717a0692-45ed-11e7-90ac-2b476582699f.png)

![image](https://cloud.githubusercontent.com/assets/7660642/26637525/b269ca7a-45ed-11e7-8305-d4b9e5cc8cbd.png)

```ffmpeg -i https://cp-open.s3.amazonaws.com/source.mp4 -codec copy -f flv - | flv+srt - caption.srt - | ffmpeg -i - -codec copy source_embeded.mp4```

URLS
Source: https://cp-open.s3.amazonaws.com/source.mp4
Source with embedded 608: https://cp-open.s3.amazonaws.com/source_embedded.mp4
SCC: https://cp-open.s3.amazonaws.com/caption.scc
SRT: https://cp-open.s3.amazonaws.com/caption.srt

**Comment by szatmary** [comment]
I suspect this was caused when I added support for fifos.  I wonder if they are detected if the `ffmpeg -analyzeduration` is increased.

**Comment by ballerabdude** [comment]
This seems to be working and fixed the the the latest build

**Comment by embeddedguy1138** [comment]
I'm having this same issue, building with the latest master branch.

**Comment by szatmary** [comment]
Does the develop branch work for you?
