### ISSUE TITLE
Encoder support for roll-up, styles, etc

### ISSUE THREAD

**Issue by embeddedguy1138** [szatmary/libcaption#29]
Does libcaption currently support changing the color, position, display mode or any other advanced features?  In caption.c, I see references to eia608_style_white, CAPTION_ROLL_UP and underline, while the other eia608_style_COLORS are defined in eia608.h.  But I don't see many examples of how this is being used.

In my own application that is based on flv+srt.c, I modified **caption_frame_from_text(frame, data, _unsigned int sty_)** to allow me to pass any style option to **caption_frame_write_char()** instead of the default _eia608_style_white__  that was there previously.  This sets the style into **cell->sty**, but I cannot figure out how cell gets used.  And I do not see any changes to the data that is being written into the video file.

I have also tried changing the frame state by setting **frame.state.sty**, **frame.state.mod** and **frame.state.rup** to other appropriate values but did not see differences to the caption data this way either.  Are these stubs to be filled out at a later time?

I would like to thank you for all the great work you have put into this library.  I was able to embed captions into my encoder just by following your example in flv+srt.  You have done a great service for the community!  Please let me know if there is anything I can do to help improve it in the future.

**Comment by embeddedguy1138** [comment]
I should say that I am working out of master.  Should I be looking at the develop branch instead?  

Thanks

**Comment by szatmary** [comment]
Its probably a good idea to work from develop. I *attempt* to use git-flow for master/develop relationship, however I know there are some production systems using master. So Im nervous to update and break something for somebody. Rite now, the conversion from caption_frame_t is done as part of `sei_from_caption_frame` in avc.c (Which is an insane place to put it. I should move to to 608.c), and yes, It currently ignores the style when rendering. Adding it would not be TOO difficult. Would need to check the style for the first character when writing the preamble, and check for style change and insert a mid_row_change. I can put that on my todo list.

**Comment by embeddedguy1138** [comment]
Thanks for taking a look, I really appreciate it.  I'll try to tackle this on my own in the next few weeks if I get some time.  Still learning the basics of 608/708 ¯\_(ツ)_/¯.

**Comment by szatmary** [comment]
https://github.com/szatmary/libcaption/pull/30  < Untested, but this SHOULD render styles now if added to the caption_frame_t

**Comment by embeddedguy1138** [comment]
Wow that was insanely quick.  By setting the render style in caption_frame_t, do you mean like this,

`caption_frame_t frame;`
`frame.state.sty = eia608_style_green;`
`frame.state.uln = 1;`

**Comment by szatmary** [comment]
Actually, no. those fields are use when parsing. Each individual character has its own style. You can can set it via `caption_frame_write_char` https://github.com/szatmary/libcaption/blob/master/caption/caption.h#L113

**Comment by embeddedguy1138** [comment]
Can confirm.

`caption_frame_write_char(frame, r, c, eia608_style_green, 1, &cap_data[0]`

VLC is able to decode this in green and with underline.  Thank you!
