### ISSUE TITLE
EIA-608 Control Codes are not doubled when using flv+srt

### ISSUE THREAD

**Issue by ldayananda** [szatmary/libcaption#32]
Thanks for creating this library! There are hardly any OSS tools for caption insertion.

I was attempting to use `flv+srt` to insert captions, but noticed that the resulting flv did not double up control codes, in particular End of Caption. It looks like in other parts of the code this is expected when decoding EIA-608:

https://github.com/szatmary/libcaption/blob/76948917967836f82f4327477dff1aa88e92c73d/src/caption.c#L321-L324

I'm happy to submit a PR to fix this, I just want to make sure I'm on the right track. Should I be looking at how `caption_frame_from_text` is writing in the srt data?

https://github.com/szatmary/libcaption/blob/master/src/caption.c#L359

**Comment by szatmary** [comment]
https://github.com/szatmary/libcaption/pull/33
^ This is probably what you want. Note: that this PR is against the develop branch. 
Master is starting to fall pretty far behind. Ill probably merge develop into master soon.

**Comment by ldayananda** [comment]
Looks like that worked! Thanks for the quick response.
